In [2]:
import pandas as pd

In [3]:
df=pd.read_excel(r"C:\Users\user\Desktop\data\dirty_framingham.xlsx")
df

,male,age,age_group,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,Male,39,Middle Age,4,No,0,No,No,No,No,195,106.0,70.0,26.97,80,77,No
1,Female,46,Middle Age,2,No,0,No,No,No,No,250,121.0,81.0,28.73,95,76,No
2,Male,48,Middle Age,1,Yes,20,No,No,No,No,245,127.5,80.0,25.34,75,70,No
3,Female,61,Old,3,Yes,30,No,No,Yes,No,225,150.0,95.0,28.58,65,103,Yes
4,Female,46,Middle Age,3,Yes,23,No,No,No,No,285,130.0,84.0,23.10,85,85,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3666,Male,50,Middle Age,1,Yes,1,No,No,Yes,No,313,179.0,92.0,25.97,66,86,Yes
3667,Male,51,Middle Age,3,Yes,43,No,No,No,No,207,126.5,80.0,19.71,65,68,No
3668,Female,52,Middle Age,2,No,0,No,No,No,No,269,133.5,83.0,21.47,80,107,No
3669,Male,40,Middle Age,3,No,0,No,No,Yes,No,185,141.0,98.0,25.60,67,72,No
3670,Female,39,Middle Age,3,Yes,30,No,No,No,No,196,133.0,86.0,20.91,85,80,No

In [4]:
df

,male,age,age_group,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,Male,39,Middle Age,4,No,0,No,No,No,No,195,106.0,70.0,26.97,80,77,No
1,Female,46,Middle Age,2,No,0,No,No,No,No,250,121.0,81.0,28.73,95,76,No
2,Male,48,Middle Age,1,Yes,20,No,No,No,No,245,127.5,80.0,25.34,75,70,No
3,Female,61,Old,3,Yes,30,No,No,Yes,No,225,150.0,95.0,28.58,65,103,Yes
4,Female,46,Middle Age,3,Yes,23,No,No,No,No,285,130.0,84.0,23.10,85,85,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3666,Male,50,Middle Age,1,Yes,1,No,No,Yes,No,313,179.0,92.0,25.97,66,86,Yes
3667,Male,51,Middle Age,3,Yes,43,No,No,No,No,207,126.5,80.0,19.71,65,68,No
3668,Female,52,Middle Age,2,No,0,No,No,No,No,269,133.5,83.0,21.47,80,107,No
3669,Male,40,Middle Age,3,No,0,No,No,Yes,No,185,141.0,98.0,25.60,67,72,No
3670,Female,39,Middle Age,3,Yes,30,No,No,No,No,196,133.0,86.0,20.91,85,80,No

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3671 entries, 0 to 3670
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             3671 non-null   object
 1   age              3671 non-null   int64
 2   age_group        3671 non-null   object
 3   education        3671 non-null   int64
 4   currentSmoker    3671 non-null   object
 5   cigsPerDay       3671 non-null   int64
 6   BPMeds           3671 non-null   object
 7   prevalentStroke  3671 non-null   object
 8   prevalentHyp     3671 non-null   object
 9   diabetes         3671 non-null   object
 10  totChol          3671 non-null   int64
 11  sysBP            3671 non-null   float64
 12  diaBP            3671 non-null   float64
 13  BMI              3658 non-null   float64
 14  heartRate        3671 non-null   int64
 15  glucose          3671 non-null   int64
 16  TenYearCHD       3671 non-null   object
dtypes: float64(3), int64(6), object(8)
memory usage: 487.7+ KB

In [8]:
sf=pd.read_csv('machine')

In [9]:
sf.isnull().sum()

education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
age                0
dtype: int64

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [20]:
x=sf.drop(['TenYearCHD'], axis =1)

In [21]:
y=sf.TenYearCHD

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=78)

In [25]:
x_train.shape

(3392, 14)

In [26]:
x_test.shape

(848, 14)

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
lr=LogisticRegression()

In [30]:
lr.fit(x_train,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [34]:
lr.score(x_train,y_train)

0.8517099056603774