In [1]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\user\Desktop\DATA SCIENCE CLASS\DataScienceClass\exam (1).csv")

In [4]:
df

      hours_study  attendance  score
0               6          87  19.53
1               5          99  21.13
2               4          51  10.73
3               5          62  13.73
4               3          67  13.13
...           ...         ...    ...
1995            6          83  18.73
1996            2          85  15.93
1997            2          99  18.73
1998            4          51  10.73
1999            1          54   8.93

[2000 rows x 3 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   hours_study  2000 non-null   int64
 1   attendance   2000 non-null   int64
 2   score        2000 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 47.0 KB

In [6]:
df.isnull().sum()

hours_study    0
attendance     0
score          0
dtype: int64

In [93]:
df.describe()

       hours_study   attendance        score
count  2000.000000  2000.000000  2000.000000
mean      3.535500    74.678500    15.094100
std       1.709152    14.410863     3.210602
min       1.000000    50.000000     8.130000
25%       2.000000    62.000000    12.530000
50%       4.000000    75.000000    15.130000
75%       5.000000    87.000000    17.730000
max       6.000000    99.000000    21.930000

In [94]:
import seaborn as sns

In [97]:
y=df.score
y

0       19.53
1       21.13
2       10.73
3       13.73
4       13.13
        ...
1995    18.73
1996    15.93
1997    18.73
1998    10.73
1999     8.93
Name: score, Length: 2000, dtype: float64

In [98]:
x=df.drop('score',axis=1)
x

      hours_study  attendance
0               6          87
1               5          99
2               4          51
3               5          62
4               3          67
...           ...         ...
1995            6          83
1996            2          85
1997            2          99
1998            4          51
1999            1          54

[2000 rows x 2 columns]

In [126]:
x_train.shape

(1600, 2)

x_train =df.iloc[:1600]
x_test=df.iloc[1600:]

In [99]:
y.shape

(2000,)

x_train.shape
x_test.shape

In [128]:
y.shape
y_train =y.iloc[:1600]
y_test=y.iloc[1600:]
y_test.shape

(400,)

In [100]:
x.shape

(2000, 2)

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=40,test_size=.20)

In [110]:
from sklearn.ensemble import RandomForestRegressor

In [112]:
model=RandomForestRegressor()

In [113]:
model.fit(x_train,y_train)

RandomForestRegressor()

In [121]:
y_pred=model.predict(x_test)

In [122]:
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error, mean_squared_error

In [123]:
mse=mean_absolute_error(y_pred,y_test)

In [124]:
mse

0.004325000000006969

In [125]:
mean_squared_error(y_pred,y_test)

0.00011500999999999081